name: pdalpy
channels:
  - conda-forge
dependencies:
  - pdal
  - shapely
  - pip:
    - aiofiles==25.1.0
    - aiohappyeyeballs==2.7.1
    - aiohttp==3.14.1
    - aiosignal==1.4.0
    - asyncio==4.0.0
    - attrs==26.1.0
    - certifi==2026.6.17
    - charset-normalizer==3.4.9
    - docopt==0.6.2
    - frozenlist==1.8.0
    - idna==3.18
    - jsonschema==4.26.0
    - jsonschema-specifications==2025.9.1
    - multidict==6.7.1
    - pipreqs==0.4.13
    - propcache==0.5.2
    - pystac==1.15.1
    - pystac-client==0.9.0
    - pystac-core==1.15.1
    - pystac-ext-classification==2.0.0
    - pystac-ext-datacube==2.2.0
    - pystac-ext-eo==1.1.0
    - pystac-ext-file==2.1.0
    - pystac-ext-grid==1.1.0
    - pystac-ext-item-assets==1.0.0
    - pystac-ext-label==1.0.1
    - pystac-ext-mgrs==1.0.0
    - pystac-ext-mlm==1.4.0
    - pystac-ext-pointcloud==1.0.0
    - pystac-ext-projection==2.0.0
    - pystac-ext-raster==1.1.0
    - pystac-ext-render==2.0.0
    - pystac-ext-sar==1.0.0
    - pystac-ext-sat==1.0.0
    - pystac-ext-scientific==1.0.0
    - pystac-ext-storage==2.0.0
    - pystac-ext-table==1.2.0
    - pystac-ext-timestamps==1.1.0
    - pystac-ext-version==1.2.0
    - pystac-ext-view==1.0.0
    - pystac-ext-xarray-assets==1.0.0
    - python-dateutil==2.9.0.post0
    - referencing==0.37.0
    - requests==2.34.2
    - rpds-py==2026.6.3
    - six==1.17.0
    - urllib3==2.7.0
    - yarg==0.1.10
    - yarl==1.24.2
