name: lidar-classification
channels:
  - conda-forge
dependencies:
  - duckdb
  - geopandas
  - ipykernel
  - overturemaps
  - pdal
  - pip
  - scipy
  - shapely
  - pip:
    - Authlib==1.7.2
    - Deprecated==1.3.1
    - PyJWT==2.13.0
    - PyNaCl==1.6.2
    - PySocks==1.7.1
    - PyYAML==6.0.3
    - Pygments==2.20.0
    - SecretStorage==3.5.0
    - affine==2.4.0
    - aiofile==3.12.3
    - aiofiles==25.1.0
    - aiohappyeyeballs==2.7.1
    - aiohttp==3.14.3
    - aiosignal==1.4.0
    - annotated-types==0.8.0
    - anyio==4.14.2
    - asyncio==4.0.0
    - attrs==26.1.0
    - awscli==1.46.0
    - backoff==2.2.1
    - bcrypt==5.0.0
    - beartype==0.22.9
    - bokeh==3.9.2
    - boto3==1.43.68
    - botocore==1.43.68
    - cachetools==7.1.7
    - caio==0.12.2
    - certifi==2026.7.22
    - cffi==2.1.1
    - charset-normalizer==3.4.9
    - click==8.4.2
    - cligj==0.7.2
    - cloudpickle==3.1.2
    - coiled==1.135.2
    - cryptography==50.0.0
    - cyclopts==4.22.5
    - dask==2026.7.1
    - decorator==5.3.1
    - distributed==2026.7.1
    - dnspython==2.8.0
    - docopt==0.6.2
    - docstring_parser==0.18.0
    - docutils==0.19
    - email-validator==2.3.0
    - exceptiongroup==1.3.1
    - fabric==3.2.3
    - fastmcp==3.4.6
    - fastmcp-slim==3.4.6
    - filelock==3.32.2
    - frozenlist==1.8.0
    - fsspec==2026.7.0
    - fused==2.8.4
    - geopandas==1.1.4
    - gilknocker==0.4.2
    - griffelib==2.1.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - httpx-sse==0.4.3
    - idna==3.18
    - invoke==2.2.1
    - jaraco.classes==3.4.0
    - jaraco.context==6.1.2
    - jaraco.functools==4.6.0
    - jeepney==0.9.0
    - jmespath==1.1.0
    - joblib==1.5.3
    - joserfc==1.7.4
    - jsondiff==2.2.1
    - jsonref==1.1.0
    - jsonschema==4.26.0
    - jsonschema-path==0.5.0
    - jsonschema-specifications==2025.9.1
    - keyring==25.7.0
    - locket==1.0.0
    - loguru==0.7.3
    - lz4==4.4.5
    - markdown-it-py==4.2.0
    - mcp==1.29.0
    - mdurl==0.1.2
    - mercantile==1.2.1
    - more-itertools==11.1.0
    - msgpack==1.2.1
    - multidict==6.7.1
    - numpy==2.5.1
    - openapi-pydantic==0.5.1
    - opentelemetry-api==1.44.0
    - outcome==1.3.0.post0
    - packaging==26.3
    - pandas==3.0.5
    - paramiko==5.0.0
    - partd==1.4.2
    - pathable==0.6.0
    - pillow==12.3.0
    - pip-requirements-parser==32.0.1
    - pipreqs==0.4.13
    - platformdirs==4.11.1
    - prometheus_client==0.26.0
    - propcache==0.5.2
    - py-key-value-aio==0.4.5
    - py4j==0.10.9.9
    - pyarrow==25.0.0
    - pyasn1==0.6.4
    - pycparser==3.0
    - pydantic==2.13.4
    - pydantic-settings==2.15.0
    - pydantic_core==2.46.4
    - pyogrio==0.13.0
    - pyparsing==3.3.2
    - pyperclip==1.11.0
    - pyproj==3.7.2
    - pystac==1.15.1
    - pystac-client==0.9.0
    - pystac-core==1.15.1
    - pystac-ext-classification==2.0.0
    - pystac-ext-datacube==2.2.0
    - pystac-ext-eo==1.1.0
    - pystac-ext-file==2.1.0
    - pystac-ext-grid==1.1.0
    - pystac-ext-item-assets==1.0.0
    - pystac-ext-label==1.0.1
    - pystac-ext-mgrs==1.0.0
    - pystac-ext-mlm==1.4.0
    - pystac-ext-pointcloud==1.0.0
    - pystac-ext-projection==2.0.0
    - pystac-ext-raster==1.1.0
    - pystac-ext-render==2.0.0
    - pystac-ext-sar==1.0.0
    - pystac-ext-sat==1.0.0
    - pystac-ext-scientific==1.0.0
    - pystac-ext-storage==2.0.0
    - pystac-ext-table==1.2.0
    - pystac-ext-timestamps==1.1.0
    - pystac-ext-version==1.2.0
    - pystac-ext-view==1.0.0
    - pystac-ext-xarray-assets==1.0.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.2
    - python-multipart==0.0.32
    - rasterio==1.5.0
    - referencing==0.37.0
    - requests==2.34.2
    - rich==15.0.0
    - rich-rst==2.1.0
    - rioxarray==0.15.7
    - rpds-py==2026.6.3
    - rsa==4.7.2
    - rtoml==0.13.0
    - s3transfer==0.19.2
    - scikit-learn==1.9.0
    - selenium==4.46.0
    - shapely==2.1.2
    - six==1.17.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - sse-starlette==3.4.8
    - starlette==1.4.1
    - tabulate==0.10.0
    - tblib==3.2.2
    - toml==0.10.2
    - toolz==1.1.0
    - tqdm==4.70.0
    - trio==0.33.0
    - trio-websocket==0.12.2
    - typing-inspection==0.4.2
    - typing_extensions==4.16.0
    - uncalled-for==0.3.2
    - urllib3==2.7.0
    - uvicorn==0.52.1
    - watchfiles==1.2.0
    - websocket-client==1.9.0
    - websockets==17.0.1
    - wheel==0.48.0
    - wsproto==1.3.2
    - xarray==2024.3.0
    - yarg==0.1.10
    - yarl==1.24.5
    - zict==3.0.0 
